# -*- coding: utf-8 -*-
"""Sentiment_using_rnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uz-n1z6EA9aj07c_6aIePCSgCh9GzhYS
"""

from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.datasets import imdb
from keras import Sequential
from keras.layers import SimpleRNN,Dense, Embedding

(X_train, Y_train ) , (X_test,Y_test)= imdb.load_data(num_words=10000)

X_train.shape

len(X_train[1])





from keras.utils import pad_sequences
X_train= pad_sequences(X_train , maxlen=200,padding='post')
X_test= pad_sequences(X_test ,maxlen=200 ,padding='post')

X_train.shape

model= Sequential()
model.add(Embedding(input_dim=10000,output_dim=2,input_shape=(200,)))
model.add(SimpleRNN(32, return_sequences=False )) # return sequences o/p is
model.add(Dense(1,activation='sigmoid'))

print(X_train.shape)
print(X_train.dtype)
print(X_train.max())
print(X_train.min())
print(Y_train.shape)
print(Y_train.dtype)

model.summary()

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train,Y_train,epochs=5,validation_data=(X_test,Y_test))